[package]
name = "sqlgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "derive", "macros", "uuid", "json"] }
tokio = { version = "1", features = ["full"] }
